### ISSUE TITLE
[Bug] Cannot Authenticate Trakt

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#10]
I'm getting this error when trying to authenticate Trakt in settings:

```2019-11-29 13:36:58.047 T:10500   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'status_code'
                                            Traceback (most recent call last):
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 52, in __init__
                                                self.router()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 514, in router
                                                self.list_trakt()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 433, in list_trakt
                                                self.params['user_slug'] = self.params.get('user_slug') or _traktapi.get_usernameslug()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 215, in get_usernameslug
                                                item = self.get_response('users/settings').json()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.4 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\traktapi.py", line 109, in get_response
                                                if response.status_code == 401:
                                            AttributeError: 'dict' object has no attribute 'status_code'
                                            -->End of Python script error report<--```

**Comment by drinfernoo** [comment]
I'm also unable to view any lists in the Trakt section without authenticating, but the dialog box it shows mentions missing API keys, even though I have entered both a TMDb *and* OMDB key.

**Comment by jurialmunkey** [comment]
Oops! Yes wrong error message in dialog -- Instead, it should say something like "Missing/Invalid Trakt Token" "You must Authenticate your Trakt account to use this feature".

Regardless, the authentication bug was my fault and caused by recent updates to trakt management functions. Should hopefully be fixed now.

**Comment by drinfernoo** [comment]
I updated the version on repo, but the version number is the same, so Kodi is having trouble finding an update.. Probably due to GitHub caching the old `.zip` file. Hopefully I'll be able to test later this afternoon.

**Comment by jurialmunkey** [comment]
I've bumped the version if you want to update again.

**Comment by drinfernoo** [comment]
Sweet, working now :)
