### ISSUE TITLE
[Question] Custom Search Path

### ISSUE THREAD

**Issue by minixb4286** [jurialmunkey/plugin.video.themoviedb.helper#144]
Hi
I used the Google Translator. Please understand if my words are strange.
I set custom search using WATCHA add on in Arctic Horizon skin, but got the below error.
WATCHA is a Korean-style streaming media similar to NETFLIX.
What should I do to fix this? Should I contact the creator of WATHCA add on?

`2020-04-01 15:07:28.543 T:1164   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: '1\xea\xb7\xb9\xed\x95\x9c\xec\xa7\x81\xec\x97\x85'
                                            Traceback (most recent call last):
                                              File "C:\Users\XB\AppData\Roaming\Kodi\addons\plugin.video.watchaM\watchaMain.py", line 766, in <module>
                                                oOOoo ( iIIi1i1 )
                                              File "C:\Users\XB\AppData\Roaming\Kodi\addons\plugin.video.watchaM\watchaMain.py", line 546, in oOOoo
                                                oooO0 = int ( args . get ( 'page' ) )
                                            ValueError: invalid literal for int() with base 10: '1\xea\xb7\xb9\xed\x95\x9c\xec\xa7\x81\xec\x97\x85'
                                            -->End of Python script error report<--
2020-04-01 15:07:28.649 T:7388   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.watchaM/?api_path=-&mode=SEARCH&stype=-&page=1극한직업
2020-04-01 15:07:32.718 T:19776 WARNING: Invalid media type "image"`

**Comment by jurialmunkey** [comment]
Yes, you will need to contact the WATCHA creator.
