### ISSUE TITLE
Decode error in dialog window for context  add to trakt history

### ISSUE THREAD

**Issue by xngsrs** [jurialmunkey/plugin.video.themoviedb.helper#156]
Hi, I have the following error for titles who have special characters in it, when trying to Add that movie in Trakt history.For example, the title "Once Upon a Time...in Hollywood" is raising the following error:

> 2020-04-11 12:37:57.921 T:3407868736   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=dir_discover&nextpage=True
2020-04-11 12:37:57.940 T:4089536528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?info=dir_discover&nextpage=True) failed
2020-04-11 12:38:00.571 T:4089536528   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-04-11 12:38:48.253 T:3176125248   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=user_discover&label=Add%20Rule...&method=add_rule&nextpage=True&type=movie
2020-04-11 12:38:48.257 T:4089536528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?info=user_discover&label=Add%20Rule...&method=add_rule&nextpage=True&type=movie) failed
2020-04-11 12:38:52.937 T:4089536528   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-04-11 12:51:09.773 T:3159339840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/context-history.py", line 8, in <module>
                                                context.action('history')
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/context.py", line 270, in action
                                                dialog_text = dialog_text.format(label, action.capitalize(), tmdb_type, tmdb_id)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--

It is fixable with utils.try_decode_string(label) instead of label, but I cannot be sure for other languages if it will fail again

**Comment by jurialmunkey** [comment]
Thanks for the bug report. Should be fixed now.
