### ISSUE TITLE
[bug] <type 'exceptions.UnicodeEncodeError'>

### ISSUE THREAD

**Issue by minixb4286** [jurialmunkey/plugin.video.themoviedb.helper#161]
Dear, jurialmunkey
I translated the strings file into Korean today.
But I got an error for the following reasons.
I refer to [e.g.](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding) to the file 
`# coding: utf-8` 
`# This Python file uses the following encoding: utf-8`
`# -*-coding: utf-8-*-` 
I tried applying it all while changing, but the same error occurred.
I don't know anything about Python so there is nothing I can do. Please check.

2020-04-13 21:14:14.982 T:22024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
                                            Traceback (most recent call last):
\service.py", line 4, in <module> ServiceMonitor()
\resources\lib\service.py", line 21, in __init__  super(ServiceMonitor, self).__init__()
\resources\lib\plugin.py", line 36, in __init__ append_to_response=APPEND_TO_RESPONSE, mpaa_prefix=mpaa_prefix)
\resources\lib\tmdb.py", line 17, in __init__  req_api_key='api_key=******************************')
\resources\lib\requestapi.py", line 25, in __init__  self.dialog_noapikey_header = '{0} - {1}'.format(self.addon.getLocalizedString(32007), self.req_api_name)

p/s 
I got the same error in the Netflix add-on.
I think it's because of Korean.

**Comment by jurialmunkey** [comment]
Try now with latest version.

**Comment by minixb4286** [comment]
I just downloaded the best version and installed it.
Korean translation has been resolved.
But as I said, Netflix keeps getting errors.

2020-04-13 22:56:39.147 T:5693  NOTICE: Running the application...
2020-04-13 22:56:45.728 T:5725   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_watchlist&widget=True&type=movie
2020-04-13 22:56:45.728 T:5725   ERROR: GetDirectory - Error getting Submenu
2020-04-13 22:56:45.729 T:5725   ERROR: GetDirectory - Error getting include
2020-04-13 22:56:46.086 T:5746   ERROR: Previous line repeats 11 times.
2020-04-13 22:56:46.086 T:5746  NOTICE: [service.upnext] UpNextMonitor -> Service started
2020-04-13 22:56:46.135 T:5725   ERROR: GetDirectory - Error getting Submenu
2020-04-13 22:56:48.667 T:5722  NOTICE: [plugin.video.themoviedb.helper]
                                            Error: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
2020-04-13 22:56:52.082 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=142061
2020-04-13 22:56:52.082 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=142061
2020-04-13 22:56:52.094 T:5724 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=287947
2020-04-13 22:56:52.094 T:5724   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=287947
2020-04-13 22:56:52.103 T:5724 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=123025
2020-04-13 22:56:52.103 T:5724   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=123025
2020-04-13 22:56:52.132 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=36647
2020-04-13 22:56:52.132 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=36647
2020-04-13 22:56:52.146 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=30061
2020-04-13 22:56:52.146 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=30061
2020-04-13 22:56:52.149 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=15359
2020-04-13 22:56:52.149 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=15359
2020-04-13 22:56:52.151 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=251519
2020-04-13 22:56:52.151 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=251519
2020-04-13 22:56:52.155 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=40662
2020-04-13 22:56:52.155 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=40662
2020-04-13 22:56:52.161 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=382322
2020-04-13 22:56:52.162 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=382322
2020-04-13 22:56:52.183 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=8698
2020-04-13 22:56:52.183 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=8698
2020-04-13 22:56:52.195 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=65291
2020-04-13 22:56:52.195 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=65291
2020-04-13 22:56:52.196 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=634649
2020-04-13 22:56:52.196 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=634649
2020-04-13 22:56:52.198 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=364
2020-04-13 22:56:52.198 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=364
2020-04-13 22:56:52.200 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=14011
2020-04-13 22:56:52.200 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=14011
2020-04-13 22:56:52.202 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=98566
2020-04-13 22:56:52.202 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=98566
2020-04-13 22:56:52.204 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=366924
2020-04-13 22:56:52.204 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=366924
2020-04-13 22:56:52.206 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=69735
2020-04-13 22:56:52.206 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=69735
2020-04-13 22:56:52.208 T:5737 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=9738
2020-04-13 22:56:52.208 T:5737   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=9738
2020-04-13 22:56:52.231 T:5725 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=36648
2020-04-13 22:56:52.231 T:5725   ERROR: InputStream: Error opening, plugin://plugin.video.themoviedb.helper/?info=play&widget=True&type=movie&tmdb_id=36648
2020-04-13 22:57:50.331 T:5833 WARNING: Invalid media type "image"
2020-04-13 22:57:52.809 T:5835 WARNING: Previous line repeats 6 times.
2020-04-13 22:57:52.809 T:5835   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 91-93: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 11, in <module>
                                                Container().router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 1146, in router
                                                self.list_tmdb()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 928, in list_tmdb
                                                items=self.tmdb.get_list(path, *args, **kwparams),
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/tmdb.py", line 484, in get_list
                                                request = func(*args, language=self.req_language, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 124, in get_request_sc
                                                return self.get_request(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 142, in get_request
                                                cache_days=cache_days, cache_name=cache_name, cache_only=cache_only)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 63, in use_cache
                                                my_object = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 96, in get_api_request
                                                utils.kodi_log('HTTP Error Code: {0}\nRequest: {1}'.format(response.status_code, request), 1)
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 91-93: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-04-13 22:57:53.039 T:5737   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=fanart&type=tv&query=종이의 집&year=2020
2020-04-13 22:57:53.187 T:5836   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 91-93: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 11, in <module>
                                                Container().router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 1146, in router
                                                self.list_tmdb()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 928, in list_tmdb
                                                items=self.tmdb.get_list(path, *args, **kwparams),
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/tmdb.py", line 484, in get_list
                                                request = func(*args, language=self.req_language, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 124, in get_request_sc
                                                return self.get_request(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 142, in get_request
                                                cache_days=cache_days, cache_name=cache_name, cache_only=cache_only)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 63, in use_cache
                                                my_object = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/requestapi.py", line 96, in get_api_request
                                                utils.kodi_log('HTTP Error Code: {0}\nRequest: {1}'.format(response.status_code, request), 1)
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 91-93: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-04-13 22:57:53.351 T:5724   ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=posters&type=tv&query=종이의 집&year=2020
2020-04-13 22:57:55.722 T:5693  NOTICE: CWinSystemAndroid::DestroyWindow

**Comment by jurialmunkey** [comment]
Please try the new version (2.4.11). Hopefully should fix those errors in your log.

**Comment by minixb4286** [comment]
Thank you. It seems to work normally.
Since I had to go to work, I didn't do much and simply tested Netflix.
I will still attach the log.

[kodi.log](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/4472317/kodi.log)
