### ISSUE TITLE
[Bug] Error with Polish special characters when try to play

### ISSUE THREAD

**Issue by notoco** [jurialmunkey/plugin.video.themoviedb.helper#17]
When trying to play a movie using player, if the movie title contains Polish characters in the name (I chose Polish in the add-on options), an error message pops up and the player selection window does not appear
Errors in log:
```
2019-12-03 12:48:25.514 T:11148   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\xxxxxx\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.themoviedb.helper\players\
2019-12-03 12:48:25.514 T:11148   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://profile/addon_data/plugin.video.themoviedb.helper/players/
2019-12-03 12:48:25.520 T:11148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u015a' in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 432, in router
                                                self.list_play()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 199, in list_play
                                                season=self.params.get('season'), episode=self.params.get('episode'))
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 39, in __init__
                                                self.router()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 48, in router
                                                self.build_details()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 55, in build_details
                                                self.item['name'] = '{0} ({1})'.format(self.item.get('title'), self.item.get('year'))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u015a' in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-12-03 12:48:25.521 T:11148   DEBUG: CPythonInvoker::onExecutionDone(33, C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py)
```
Movie - Ślicznotki - in EN:Hustlers (2019)

**Comment by jurialmunkey** [comment]
Thanks for the bug report.

Can you test with latest version and confirm if the bug is now fixed?

**Comment by notoco** [comment]
Window to choose player is open, but when I choose - still error
```
2019-12-04 07:44:24.436 T:5956   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://profile/addon_data/plugin.video.themoviedb.helper/players/
2019-12-04 07:44:26.239 T:5956  NOTICE: [plugin.video.themoviedb.helper]
                                            Container.Update(plugin://plugin.video.netflix/directory/search/search/Ślicznotki/)
2019-12-04 07:44:26.243 T:5956   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u015a' in position 71: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 431, in router
                                                self.list_play()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 198, in list_play
                                                season=self.params.get('season'), episode=self.params.get('episode'))
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 38, in __init__
                                                self.router()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 48, in router
                                                self.build_selectbox()
                                              File "C:\Users\xxxxxx\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\player.py", line 144, in build_selectbox
                                                xbmc.executebuiltin(actions[itemindex])
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u015a' in position 71: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by jurialmunkey** [comment]
Okay, hopefully should be fixed now! 🤞

**Comment by notoco** [comment]
works!
