### ISSUE TITLE
[Bug] Error Contents: 'ascii' codec can't encode character u'\xe6' 

### ISSUE THREAD

**Issue by mLgz0rn** [jurialmunkey/plugin.video.themoviedb.helper#230]
```
2020-05-18 01:54:05.517 T:29097  NOTICE: [plugin.video.themoviedb.helper]
                                            UPDATING TV SHOWS LIBRARY
2020-05-18 01:54:07.498 T:29097   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe6' in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 10, in <module>
                                                TMDbScript.router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 491, in router
                                                self.library_autoupdate()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 403, in library_autoupdate
                                                context.library_userlist(user_slug=user_slug, list_slug=list_slug, confirmation_dialog=False, allow_update=False, busy_dialog=busy_dialog)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/context.py", line 270, in library_userlist
                                                library_addtvshow(basedir=basedir_tv, folder=folder, url=content, tmdb_id=tmdb_id, imdb_id=imdb_id, tvdb_id=tvdb_id, p_dialog=p_dialog)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/context.py", line 130, in library_addtvshow
                                                season_name = '{} {}'.format(xbmc.getLocalizedString(20373), season)  # This was a dumb idea to localise season name - too late now
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--
```
I have yet to get the local library integration to work.
The above is the error I get when it tries to update the library.

The only tvshow getting added, or should I say folder is "the flash" 
![IMG_20200518_020149](https://user-images.githubusercontent.com/6141439/82163452-954e7d00-98ab-11ea-98ec-29c80bad44e3.jpg)
And this is the only thing present in that folder.
Deleting the folder and restarting kodi, just ends up with the same thing.

Best regards.

**Comment by jurialmunkey** [comment]
What Kodi version? 
What language is set in Kodi settings and in TMDbHelper settings?

**Comment by mLgz0rn** [comment]
> What Kodi version?
> What language is set in Kodi settings and in TMDbHelper settings?

Kodi 18.6
Kodi language is set to Danish
TMDbHelper language is set to Danish

**Comment by jurialmunkey** [comment]
@mLgz0rn - Hopefully should be fixed now.

**Comment by mLgz0rn** [comment]
@jurialmunkey 
Awesome! seems to be working now!
Stuff are being added to folders :D
