### ISSUE TITLE
[Bug] Search Menu Error

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#272]
In a recent version, it appears that having "search history" items in the "Search" menu makes the menu crash with the following error:
```python
2020-07-21 14:42:01.541 T:9036   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'unicode' object does not support item assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\David\Desktop\kodi\Leia 18.7 Testing\portable_data\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                Container().router()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.7 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 1293, in router
                                                self.list_searchdir()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.7 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 1011, in list_searchdir
                                                self.list_clearhistory(url=url.pop('query', ''), icon=icon)
                                              File "C:\Users\David\Desktop\kodi\Leia 18.7 Testing\portable_data\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 940, in list_clearhistory
                                                url['clearcache'] = 'True'
                                            TypeError: 'unicode' object does not support item assignment
                                            -->End of Python script error report<--
```
This doesn't happen on a fresh install, as there are no history items to show, but after one search has been performed, the menu will no longer open.

**Comment by jurialmunkey** [comment]
Ah yep just realised this now when I went to search - I think I didn't notice it before because I had cleared the history.
