### ISSUE TITLE
Trakt In-Progress Shows / Next episodes breaks if simplecache.db deleted in 3.2.1 or 3.2.2

### ISSUE THREAD

**Issue by meesterexx** [jurialmunkey/plugin.video.themoviedb.helper#273]
When I move my build to my NAS, I always delete thumbnails / temp files / packages / simplecache.db to reduce size. Starting in 3.2.1 & continuing in 3.2.2, tmdbhelper started throwing the below error in the log for my widget, and on testing I found neither in progress shows or next episodes was working, but things like watchlist and history were. The fix was to roll back to 3.1.7 then update back to 3.2.2. After testing which part of my deletions before move were causing the error I found that deleting simplecache.db from user_data caused the issue. Please note the issue does not occur in 3.1.7 if simplecache.db is deleted. Also of note, the intial simplecache.db created on my kodi by 3.2.2 is only 118k and the one created by 3.1.7 is 1.5Mb.   For now, I'm backing up the build with simplecache.db included to avoid the issue:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
                                            
Traceback (most recent call last):
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 11, in <module>
Container().router()
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 1309, in router
self.list_trakthistory()
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container.py", line 560, in list_trakthistory
items = traktapi.get_inprogress_movies(limit=self.trakt_limit) if self.params.get('type') == 'movie' else traktapi.get_inprogress(userslug, limit=self.trakt_limit)
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/traktapi.py", line 351, in get_inprogress
progress = self.get_upnext(i[0], True, last_updated=last_updated)
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/traktapi.py", line 451, in get_upnext
cache_refresh = self.get_upnext_cache_refresh(show_id, last_updated)
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/traktapi.py", line 439, in get_upnext_cache_refresh
ts_prev = utils.convert_timestamp(self.get_cache(cache_name))
File "/home/user/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/utils.py", line 247, in convert_timestamp
time_str = time_str[:time_lim] if time_lim else time_str
TypeError: 'NoneType' object has no attribute '__getitem__'
-->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_inprogress&widget=True&type=tv
ERROR: GetDirectory - Error getting Submenu
ERROR: GetDirectory - Error getting include
ERROR: Previous line repeats 1 times.
ERROR: GetDirectory - Error getting Submenu

**Comment by jurialmunkey** [comment]
You shouldn't be deleting simplecache.db 

Simplecache is used to cache data from the APIs and prevent excessive number of requests. Simplecache uses expiry dates to clean itself.

**Comment by jurialmunkey** [comment]
Should be fixed now. Thanks for the bug report!
