### ISSUE TITLE
Can't authenticate tract

### ISSUE THREAD

**Issue by daanvandevliet** [jurialmunkey/plugin.video.themoviedb.helper#288]
Thank you for making this plugin.

TheMovieDb Helper: 3.3.12
Kodi: 18.8

Behavior: Open TheMovieDb Helper, Accounts, click: "Authenticate Trakt"
TheMovieDb Helper exits and I get thrown to a parent screen. No popup or anything.

```
2020-08-20 21:54:31.457 T:139626618541824   DEBUG: CPythonInvoker(884, /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/script.py): setting the Python path to /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper:/usr/share/kodi/addons/script.module.pil/lib:/var/lib/kodi/.kodi/addons/script.module.certifi/lib:/var/lib/kodi/.kodi/addons/script.module.chardet/lib:/var/lib/kodi/.kodi/addons/script.module.idna/lib:/var/lib/kodi/.kodi/addons/script.module.requests/lib:/var/lib/kodi/.kodi/addons/script.module.simplecache/lib:/var/lib/kodi/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages
2020-08-20 21:54:31.457 T:139626618541824   DEBUG: CPythonInvoker(884, /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/script.py): entering source directory /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper
2020-08-20 21:54:31.457 T:139626618541824   DEBUG: CPythonInvoker(884, /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/script.py): instantiating addon using automatically obtained id of "plugin.video.themoviedb.helper" dependent on version 2.26.0 of the xbmc.python api
2020-08-20 21:54:31.492 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-08-20 21:54:31.492 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-08-20 21:54:31.493 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-08-20 21:54:31.635 T:139626618541824   DEBUG: Skin Helper Simplecache --> Initialized
2020-08-20 21:54:31.637 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-08-20 21:54:31.638 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-08-20 21:54:31.638 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-08-20 21:54:31.641 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-08-20 21:54:31.641 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-08-20 21:54:31.642 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-08-20 21:54:31.642 T:139626618541824   DEBUG: Skin Helper Simplecache --> Initialized
2020-08-20 21:54:31.643 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-08-20 21:54:31.643 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-08-20 21:54:31.643 T:139626618541824   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-08-20 21:54:31.658 T:139626618541824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 5, in <module>
                                                from resources.lib.script import Script
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 17, in <module>
                                                from resources.lib.service import ServiceMonitor, ImageFunctions
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/service.py", line 10, in <module>
                                                from PIL import ImageFilter, Image
                                              File "/usr/lib/python2.7/site-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/site-packages/numpy/core/multiarray.py", line 13, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/site-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
2020-08-20 21:54:31.661 T:139626618541824   DEBUG: onExecutionDone(884, /var/lib/kodi/.kodi/addons/plugin.video.themoviedb.helper/script.py)
2020-08-20 21:54:31.662 T:139628564452608   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-08-20 21:54:31.669 T:139628564452608   DEBUG: ------ Window Deinit (DialogAddonSettings.xml) ------
2020-08-20 21:54:31.833 T:139626618541824   DEBUG: Skin Helper Simplecache --> Closed
2020-08-20 21:54:31.842 T:139626618541824   DEBUG: Previous line repeats 1 times.
2020-08-20 21:54:31.842 T:139626618541824    INFO: Python interpreter stopped

```

**Comment by jurialmunkey** [comment]
I assume you're using Manjaro or some derivative of it. It's an issue with the way that distro overwrites Kodi's built-in python module. Specifically, it's an issue with the version of numpy that it ships.

Fix is here: 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/244#issuecomment-639737411
