### ISSUE TITLE
TMDB helper (v3.3.20) error in Kodi 18.8

### ISSUE THREAD

**Issue by crypt3dC4rb0n** [jurialmunkey/plugin.video.themoviedb.helper#301]
Got the following error after installing the TMDB helper. Tried other versions as well but didn't worked. 

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/ubuntu/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 5, in <module>
                                                from resources.lib.script import Script
                                              File "/home/ubuntu/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 16, in <module>
                                                from resources.lib.service import ServiceMonitor, BlurImage
                                              File "/home/ubuntu/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/service.py", line 8, in <module>
                                                from PIL import ImageFilter, Image
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 13, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
```

**Comment by drinfernoo** [comment]
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/288#issuecomment-677999215
