### ISSUE TITLE
Error when selecting "Play"

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/plugin.video.themoviedb.helper#314]
Using v 4.0.11 on Matrix Alpha 2. When selecting "Play" the following error occurs:

```
 Error Type: <class 'TypeError'>
 Error Contents: '<' not supported between instances of 'NoneType' and 'int'
 Traceback (most recent call last):
 File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\script.py", line 8, in <module>
       Script().router()
 File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\script\router.py", line 237, in router  return WindowManager(**self.params).router()
  File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\window\manager.py", line 152, in __init__  self.kodi_id = self.window_id + 10000 if self.window_id < 10000 else self.window_id
 TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

I'm new to Python but think this is due to changes between versions 2 and 3. As a simple test I changed line 151 in resources\lib\window\manager.py from:
self.window_id = try_int(kwargs['call_auto']) if kwargs.get('call_auto') else none
to:
self.window_id = try_int(kwargs['call_auto']) if kwargs.get('call_auto') else 0

This stopped the error and the video played ok, but have no idea if this is a good fix or not!

**Comment by jurialmunkey** [comment]
What do you mean by "selecting Play"? Is this via your remote? The info dialog? A button in a skin? If it's the info dialog or a skin button, then what skin is it?

**Comment by jurialmunkey** [comment]
Latest version (v4.0.14) should fix this issue. I tested in Arctic Horizon and play button is now working correctly there. Not sure if there's still an issue in other skins.

**Comment by berkhornet** [comment]
Many thanks. Tested here with Arctic Horizon and all good.
