### ISSUE TITLE
Local videos not playing from TMDB Helper Trakt next up Widget

### ISSUE THREAD

**Issue by roc16** [jurialmunkey/plugin.video.themoviedb.helper#339]
Hi Jurialmunkey, I think this is similar to ticket 332 however it is not working for me with the latest installs. Any help is appreciated. 

Issue description
I have the TMDB helper Trakt next up widget setup, however no local files will play from the widget. I get a pop-up asking to choose a player and the only option is play with UPnP. All was working ok until the v4 upgrade. Let me know if you need a log. 

Installed versions
Everything was installed from scratch today and I am using plexkodiconnect add on for native Plex kodi integration (I’m pretty sure you have heard of it?)
Skin Arctic Horizon 0.5.51
TMDB helper 4.0.33
PlexKodiConnect 2.12.3
OS Coreelec 9.2.5

**Comment by roc16** [comment]
log is at the below if you need it
https://pastebin.com/RH0XrACQ

**Comment by 7E1EVEN** [comment]
I'm having the same issue. It still works for local movies though.
But local TV Shows cannot be found.

Part of log:

> 2020-11-08 10:56:56.805 T:3664724192   ERROR: Previous line repeats 1 times.
2020-11-08 10:56:56.805 T:3664724192   ERROR: Traceback (most recent call last):
2020-11-08 10:56:56.806 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 57, in sync_activities
2020-11-08 10:56:56.962 T:3664724192   ERROR:     success = self._remove_old_meta_items('shows')
2020-11-08 10:56:56.963 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 606, in _remove_old_meta_items
2020-11-08 10:56:56.963 T:3664724192   ERROR:     for i in range(2, int(trakt_api.response_headers['X-Pagination-Page-Count']) + 1):
2020-11-08 10:56:56.964 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
2020-11-08 10:56:56.965 T:3664724192   ERROR:     return self._store[key.lower()][1]
2020-11-08 10:56:56.965 T:3664724192   ERROR: KeyError: 'x-pagination-page-count'
2020-11-08 10:56:58.577 T:3664724192   ERROR: Traceback (most recent call last):
2020-11-08 10:56:58.578 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 75, in sync_activities
2020-11-08 10:56:58.579 T:3664724192   ERROR:     success = self._remove_old_meta_items('movies')
2020-11-08 10:56:58.579 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.seren/resources/lib/modules/trakt_sync/activities.py", line 606, in _remove_old_meta_items
2020-11-08 10:56:58.582 T:3664724192   ERROR:     for i in range(2, int(trakt_api.response_headers['X-Pagination-Page-Count']) + 1):
2020-11-08 10:56:58.582 T:3664724192   ERROR:   File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
2020-11-08 10:56:58.584 T:3664724192   ERROR:     return self._store[key.lower()][1]
2020-11-08 10:56:58.584 T:3664724192   ERROR: KeyError: 'x-pagination-page-count'
2020-11-08 10:57:03.921 T:3858747616 WARNING: Attempt to use invalid handle 2
2020-11-08 10:57:04.842 T:3191611616 WARNING: Previous line repeats 1 times.
2020-11-08 10:57:04.842 T:3191611616  NOTICE: [plugin.video.themoviedb.helper]
                                            Failed to import _strptime because the import lockis held by another thread.

**Comment by jurialmunkey** [comment]
@roc16 - I can't recreate this issue. Episodes in my local library play fine for me from the Trakt "Your Next Episodes" widget.

This line in your log indicates that TMDbHelper can't find a matching episode in the library
```
2020-11-03 09:07:09.917 T:3828130624  NOTICE: [plugin.video.themoviedb.helper]
                                            Getting KodiDB episode FAILED!
```

I suspect that PKC is not adding the required unique id info to the library database in order for TMDbHelper to be able to match the show correctly. Can you provide my your library db file so that I can see how PKC is configuring the uniqueid fields?
`.kodi/userdata/Database/MyVideos116.db`

**Comment by roc16** [comment]
[MyVideos116.db.zip](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/5522391/MyVideos116.db.zip)
@jurialmunkey thanks for the investigation so far.library db file is attached.

**Comment by jurialmunkey** [comment]
@roc16 - Thanks! The db file was a great help in locating the issue. I'm fairly certain that the latest version from master should now work for you. Can you test and confirm?

**Comment by roc16** [comment]
@jurialmunkey nice on - works now. Thanks a million! One small comment - the local library symbol does not appear on the poster (it is selected in skin settings > items and views > watched indicators). Not an issue for me at all just thought you might want to know.

**Comment by jurialmunkey** [comment]
> One small comment - the local library symbol does not appear on the poster (it is selected in skin settings > items and views > watched indicators). Not an issue for me at all just thought you might want to know.

Ah yeah, you're right. Arctic Horizon is looking for a property that no longer exists in v4 of TMDbHelper.  Pushed a fix to the AH github.
