### ISSUE TITLE
Library  integration error

### ISSUE THREAD

**Issue by spursgalea** [jurialmunkey/plugin.video.themoviedb.helper#362]
I keep getting  error when i  press update the library now is it my end or is library broken  thanks

**Comment by drinfernoo** [comment]
What's the error? There's no way to know what the issue is without it.

**Comment by spursgalea** [comment]
I should have done this to begin with.
He is my log and and a  screen record of the issue https://youtu.be/B3e-T5gGlQ8

**Comment by drinfernoo** [comment]
```python
2020-11-16 17:12:03.409 T:5989  NOTICE: [plugin.video.themoviedb.helper]
                                            UPDATING TV SHOWS LIBRARY
2020-11-16 17:12:04.951 T:5989   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: normalize() argument 2 must be unicode, not None
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 8, in <module>
                                                Script().router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 320, in router
                                                return self.routing_table[route_taken](**self.params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 298, in <lambda>
                                                'library_autoupdate': lambda **kwargs: library_update(**kwargs),
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 235, in library_update
                                                force=kwargs.get('force', False))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/userlist.py", line 67, in library_autoupdate
                                                busy_spinner=busy_spinner, force=force, library_adder=library_adder, finished=False)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 26, in add_to_library
                                                library_adder.add_userlist(**kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 90, in add_userlist
                                                playlist_rule = self._add_userlist_item(i)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 120, in _add_userlist_item
                                                return func(tmdb_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 163, in add_tvshow
                                                self._add_season(season)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 187, in _add_season
                                                self._add_episode(episode, number, folder)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/kodi/library.py", line 196, in _add_episode
                                                filename = u'S{:02d}E{:02d} - {}'.format(try_int(season), try_int(number), validify_filename(episode.get('name')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/files/utils.py", line 29, in validify_filename
                                                filename = str(unicodedata.normalize('NFD', filename).encode('ascii', 'ignore').decode("utf-8"))
                                            TypeError: normalize() argument 2 must be unicode, not None
                                            -->End of Python script error report<--
```

**Comment by spursgalea** [comment]
I was not sure I was allowed to post logs here thanks

**Comment by jurialmunkey** [comment]
Could you try latest git master and see if that fixes the issue?

**Comment by spursgalea** [comment]
it's fixed thank you
