### ISSUE TITLE
library update errors

### ISSUE THREAD

**Issue by smallieollie** [jurialmunkey/plugin.video.themoviedb.helper#365]
it seems as though since the 13th of November I am getting an error on both my setups.  Neither has had a successful update since then..  I am working away from home so i am limited on info I can gather from significant other.  I am on version 4.0.45.  I thought i had it narrowed down to a specific show, but i removed that show(crime beat) from my library and trakt list cleaned library and could tell that it got multiple shows past crime beat and then errored out again at what i think is naked and afraid xl.  below is a pasted version from the log.  if you need the full log i can get it to you, but it might not be for a couple days as i am away.  THANKS IN ADVANCE

```python
20-11-17 19:43:26.969 T:8324  NOTICE: [plugin.video.themoviedb.helper]
                                            UPDATING TV SHOWS LIBRARY
2020-11-17 19:43:48.281 T:8324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: normalize() argument 2 must be unicode, not None
                                            Traceback (most recent call last):
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\script.py", line 8, in <module>
                                                Script().router()
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\script\router.py", line 312, in router
                                                return library_update(**self.params)
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\script\router.py", line 233, in library_update
                                                force=kwargs.get('force', False))
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\kodi\update.py", line 484, in library_autoupdate
                                                add_userlist(user_slug, list_slug, confirm=False, allow_update=False, busy_spinner=busy_spinner, force=force)
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\kodi\update.py", line 418, in add_userlist
                                                tmdb_id=tmdb_id, imdb_id=imdb_id, tvdb_id=tvdb_id, p_dialog=p_dialog, force=force)
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\kodi\update.py", line 289, in add_tvshow
                                                validify_filename(episode.get('name')))
                                              File "C:\Users\caela\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\files\utils.py", line 29, in validify_filename
                                                filename = str(unicodedata.normalize('NFD', filename).encode('ascii', 'ignore').decode("utf-8"))
                                            TypeError: normalize() argument 2 must be unicode, not None
                                            -->End of Python script error report<--
```

**Comment by jurialmunkey** [comment]
Please update to latest git version (which v4.0.51) as I believe that I have already fixed this issue here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/362

**Comment by smallieollie** [comment]
Man you are a work horse!  I just updated before I left, you have been busy!  I will have the wife update and will report back before tomorrow evening and close out issue if resolved.

**Comment by smallieollie** [comment]
Issue resolved!  Thanks again for all you do!
