### ISSUE TITLE
[BUG][Matrix] Update Players not working

### ISSUE THREAD

**Issue by Nadarob-Skillane** [jurialmunkey/plugin.video.themoviedb.helper#416]
Not saving the file from http://bit.ly/tmdbplayers correctly.

```
                                                   URL check passed for http://bit.ly/tmdbplayers: Status code [200]
2021-01-22 16:16:54.021 T:9221    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: write() argument must be str, not bytes
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 7, in <module>
                                                       Script().router()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 358, in router
                                                       return self.routing_table[route_taken](**self.params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 328, in <lambda>
                                                       'update_players': lambda **kwargs: update_players(),
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 182, in update_players
                                                       downloader.get_extracted_zip()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/files/downloader.py", line 158, in get_extracted_zip
                                                       target.write(_file.read())
                                                   TypeError: write() argument must be str, not bytes
                                                   -->End of Python script error report<--
```

**Comment by briangot2** [comment]
you can manually unzip it , then copy the players into your "userdata/addon_data/plugin.video.themoviedb.helper/players" folder.

**Comment by jurialmunkey** [comment]
Please try latest version from matrix branch. Should be fixed now.

**Comment by Nadarob-Skillane** [comment]
Sorry for the delay. This worked perfectly.
Thanks :D
