### ISSUE TITLE
i can't use fanarttv.tv for additional artwork

### ISSUE THREAD

**Issue by taxdriver4u** [jurialmunkey/plugin.video.themoviedb.helper#456]
i hope using additional artwork

so i have applyed fanart.tv. client key and enabled below options

![fanart](https://user-images.githubusercontent.com/44728502/110940895-f2f01080-837a-11eb-80bb-281214e330eb.JPG)

but error happened

![tmdb](https://user-images.githubusercontent.com/44728502/110941102-2337af00-837b-11eb-9d43-db9442b07f8b.JPG)

log

2021-03-12 21:23:08.311 T:18412   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'str' and 'int'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 11, in <module>
                                                       Container().router()
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 1149, in router
                                                       self.list_tmdb()
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 930, in list_tmdb
                                                       self.list_items(
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container.py", line 906, in list_items
                                                       i.get_extra_artwork(self.tmdb, self.fanarttv) if len(items) < 22 and self.exp_fanarttv() else None
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\listitem.py", line 94, in get_extra_artwork
                                                       artwork = fanarttv.get_movie_allart_lc(self.tmdb_id)
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\fanarttv.py", line 153, in get_movie_allart_lc
                                                       return self.use_cache(
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\requestapi.py", line 63, in use_cache
                                                       my_object = func(*args, **kwargs)
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\fanarttv.py", line 137, in get_movie_allart
                                                       discart = self.get_movie_discart(ftvid, *args, **kwargs)
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\fanarttv.py", line 84, in get_movie_discart
                                                       return self.get_artwork_lc(True, ftvid, 'movies', 'moviedisc', *args, **kwargs)
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\fanarttv.py", line 59, in get_artwork_lc
                                                       return self.use_cache(
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\requestapi.py", line 63, in use_cache
                                                       my_object = func(*args, **kwargs)
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\fanarttv.py", line 45, in get_artwork_best
                                                       elif i.get('likes', 0) > best_like:
                                                   TypeError: '>' not supported between instances of 'str' and 'int'
                                                   -->End of Python script error report<--
                                                   
2021-03-12 21:23:08.415 T:18412    INFO <general>: Python interpreter stopped

**Comment by drinfernoo** [comment]
What version of TMDbHelper do you have installed?

**Comment by jurialmunkey** [comment]
Looks like official repo version. Please update to latest version from my repo or this github.

**Comment by drinfernoo** [comment]
@jurialmunkey Thought so, but couldn't tell right off from the attached error 👍

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Thought so, but couldn't tell right off from the attached error 👍

No subfolders in `resources/lib` is the giveaway - v4 moved modules into subfolders.
