### ISSUE TITLE
Error Contents: list_tmdb() missing 1 required positional argument: 'tmdb_type'

### ISSUE THREAD

**Issue by heppix** [jurialmunkey/plugin.video.themoviedb.helper#500]
Hello,
When I try to play trailer from "YouTube" section in TMDb helper, from widgets set on Home screen, there is error like so:

```
2021-05-27 20:14:33.911 T:17684   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: list_tmdb() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 8, in <module>
                                                       Container().router()
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 380, in router
                                                       return self.get_directory()
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 344, in get_directory
                                                       items = self.get_items(**self.params)
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 341, in get_items
                                                       return self._get_items(route[info]['route'], **kwargs)
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 312, in _get_items
                                                       return func['lambda'](getattr(self, func['getattr']), **kwargs)
                                                     File "C:\Users\piotr\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\constants.py", line 138, in <lambda>
                                                       'lambda': lambda func, **kwargs: func(**kwargs),
                                                   TypeError: list_tmdb() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--
                                                   
2021-05-27 20:14:34.076 T:17684    INFO <general>: Python interpreter stopped
```

It's not appear if I play trailer from "Trailer" button.
I'm using skin Arctic Zephyr 2 on Kodi 19.1.

Is there any solution for this?

**Comment by jurialmunkey** [comment]
Skin issue. Arctic zephyr 2 does not have a Matrix version and is no longer developed.
