### ISSUE TITLE
After updating tmdb helper doesn't work

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#667]
These are logs from android if that matters.

```
2022-02-27 09:03:19.553 T:32337   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (api.py, line 44)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/service.py", line 1, in <module>
                                                       from resources.lib.monitor.service import ServiceMonitor
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/service.py", line 5, in <module>
                                                       from resources.lib.monitor.listitem import ListItemMonitor
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/listitem.py", line 5, in <module>
                                                       from resources.lib.monitor.common import CommonMonitorFunctions, SETMAIN_ARTWORK, SETPROP_RATINGS
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/common.py", line 4, in <module>
                                                       from resources.lib.api.tmdb.api import TMDb
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/api/tmdb/api.py", line 44
                                                       self.req_language = f'{self.iso_language}-{self.iso_country}&include_image_language={self.iso_language},null{',en' if ARTLANG_FALLBACK else ''}'
                                                                                                                                                                        ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
```
```
2022-02-27 09:05:35.439 T:32549   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (api.py, line 44)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 4, in <module>
                                                       from resources.lib.container.router import Container
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/container/router.py", line 12, in <module>
                                                       from resources.lib.api.tmdb.api import TMDb
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/api/tmdb/api.py", line 44
                                                       self.req_language = f'{self.iso_language}-{self.iso_country}&include_image_language={self.iso_language},null{',en' if ARTLANG_FALLBACK else ''}'
                                                                                                                                                                        ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
```

**Comment by jurialmunkey** [comment]
Whoops, my stupid mistake. Forgot to commit the fix before pushing.
