### ISSUE TITLE
Error TMDBHELPER 4.6.16

### ISSUE THREAD

**Issue by lebigboss** [jurialmunkey/plugin.video.themoviedb.helper#668]
Hello I have an error

2022-02-27 09:56:11.821 T:2601     INFO <general>: Skin Helper Service --> skin.helper.service: extrafanart
2022-02-27 09:56:11.827 T:2601  WARNING <general>: Skin Helper Service --> Exception details: Type: AttributeError Value: 'MetadataUtils' object has no attribute 'get_trakt_info' Traceback: Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 353, in set_listitem_details
                                                       details = merge_dict(details, self.metadatautils.get_trakt_info(details["imdbnumber"]))
                                                   AttributeError: 'MetadataUtils' object has no attribute 'get_trakt_info'
                                                   
2022-02-27 09:56:11.827 T:2601    ERROR <general>: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> 'MetadataUtils' object has no attribute 'get_trakt_info'
2022-02-27 09:56:11.863 T:30742    INFO <general>: [plugin.video.themoviedb.helper]
                                                   lib.monitor.listitem.get_listitem
                                                   Error Type: KeyError
                                                   Error Contents: ('artwork',)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/decorators.py", line 54, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/listitem.py", line 300, in get_listitem
                                                       artwork = details['artwork']
                                                   
2022-02-27 09:56:13.256 T:2595     INFO <general>: Skipped 1 duplicate messages..
2022-02-27 09:56:13.256 T:2595     INFO <general>: CPythonInvoker(37, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/plugin.py): script successfully run
2022-02-27 09:56:14.063 T:2595     INFO <general>: Python interpreter stopped

**Comment by jurialmunkey** [comment]
This should already be fixed in latest git version.

**Comment by lebigboss** [comment]
> This should already be fixed in latest git version.

you are too fast loll
Thank you
