### ISSUE TITLE
TMDB Helper FEN player problem

### ISSUE THREAD

**Issue by baltzis** [jurialmunkey/plugin.video.themoviedb.helper#684]
It seems that the FEN player has a problem with the new FEN version (2.6.09). It produces the following error, perhaps similar to the one previously resolved in a post at https://github.com/Tikipeter/repository.tikipeter/issues/704. With the latest version of FEN, it seems that the problem reappeared.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'title'
Traceback (most recent call last):
  File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module> routing(argv[2])
  File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\router.py", line 60, in routing Sources().playback_prep(params)
  File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 93, in playback_prep self._search_info()
  File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 327, in _search_info title = self._get_search_title(self.meta)
  File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 339, in _get_search_title if self.language == 'en': search_title = meta['title']
KeyError: 'title'
-->End of Python script error report<--

**Comment by jurialmunkey** [comment]
I don't make 3rd party players. Ask whoever made the player file to fix it.

**Comment by jurialmunkey** [comment]
I suspect you are probably looking for https://github.com/a4k-openproject/json.openplayers/tree/tmdbhelper

If your player came from there post an issue on that repo.

**Comment by baltzis** [comment]
Sorry, for posting here. Thanks for the response.
