### ISSUE TITLE
[BUG] TVDb error

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#837]
### Describe the bug

Version 4.11.3

TVDb -> Awards -> Daytime Emmy Awards -> Outstanding Culinary Series

Errors:-
```
2022-08-28 11:15:57.120 T:26551    INFO <general>: Python interpreter stopped
2022-08-28 11:15:57.131 T:26550   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=tvdb_award_category&tvdb_id=241
2022-08-28 11:15:57.137 T:10633   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.themoviedb.helper/?info=tvdb_award_category&tvdb_id=241) failed
2022-08-28 11:15:58.908 T:26565    INFO <general>: initializing python engine.
2022-08-28 11:16:00.316 T:26182   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Netflix / MRC / Panic Pictures / Trigger Street Productions.png
2022-08-28 11:16:00.511 T:26565    INFO <general>: CPythonInvoker(677, /storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py): script successfully run
2022-08-28 11:16:01.758 T:26565    INFO <general>: Python interpreter stopped
2022-08-28 11:16:03.551 T:26587    INFO <general>: initializing python engine.
2022-08-28 11:16:03.758 T:26589   ERROR <general>: Exception in thread 
2022-08-28 11:16:03.758 T:26589   ERROR <general>: Thread-2
2022-08-28 11:16:03.758 T:26589   ERROR <general>: :
                                                   
2022-08-28 11:16:03.758 T:26589   ERROR <general>: Traceback (most recent call last):
                                                   
2022-08-28 11:16:03.758 T:26589   ERROR <general>:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>:   File "/usr/lib/python3.8/threading.py", line 870, in run
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>:   File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/thread.py", line 70, in _threadwrapper
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>:     
2022-08-28 11:16:03.759 T:26589   ERROR <general>: self.queue[x] = func(i, *args, **kwargs)
2022-08-28 11:16:03.759 T:26589   ERROR <general>: 
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>:   File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/api/tvdb/lists_awards.py", line 31, in _get_item
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>:     
2022-08-28 11:16:03.759 T:26589   ERROR <general>: item['infoproperties']['plot_affix'] = f"{get_localized(32461) if i.get('isWinner') else get_localized(32462)} {award_category} {i.get('year')}"
2022-08-28 11:16:03.759 T:26589   ERROR <general>: 
                                                   
2022-08-28 11:16:03.759 T:26589   ERROR <general>: TypeError
2022-08-28 11:16:03.759 T:26589   ERROR <general>: : 
2022-08-28 11:16:03.759 T:26589   ERROR <general>: 'NoneType' object is not subscriptable
2022-08-28 11:16:03.760 T:26589   ERROR <general>: 
                                                   
2022-08-28 11:16:03.818 T:26587   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: max() arg is an empty sequence
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 46, in run
                                                       self.get_directory()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 39, in get_directory
                                                       container.get_directory()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/container.py", line 246, in get_directory
                                                       items = self.get_items(**self.params)
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/api/tvdb/lists_awards.py", line 54, in get_items
                                                       info_mediatype = max(mediatypes, key=lambda k: len(mediatypes[k]))
                                                   ValueError: max() arg is an empty sequence
                                                   -->End of Python script error report<--
```

### Steps To Reproduce

TVDb -> Awards -> Daytime Emmy Awards -> Outstanding Culinary Series

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Fixed the error. Ironically the list only has one item and TMDb doesn't have any details for it so can't display it anyway...

**Comment by roidy** [comment]
It's not something I'd ever use, I was just randomly clicking around in the new TVDb section having a look and that error popped up, so I thought I'd report it.
