### ISSUE TITLE
[BUG] Python error

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#886]
### Describe the bug

AH2 0.4.24
themoviedb.helper 5.0.6

Throws this error:-
```
2022-10-01 08:21:31.172 T:25166   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: __init__() missing 1 required positional argument: 'window_id'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 7, in <module>
                                                       Script(*sys.argv[1:]).router()
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 120, in router
                                                       return self.routing_table[route_taken](**self.params)
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 88, in <lambda>
                                                       lambda **kwargs: importmodule('resources.lib.window.recommendations', 'WindowRecommendationsManager')(**kwargs).router(),
                                                   TypeError: __init__() missing 1 required positional argument: 'window_id'
                                                   -->End of Python script error report<--
```

### Steps To Reproduce

DialogVideoInfo press down

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Update AH2 to the latest version...

**Comment by roidy** [comment]
Umm strange.... Your repo only auto updates me to 0.4.24. I'll manually install and try again. Thanks.
