### ISSUE TITLE
More Python errors :(

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/plugin.video.themoviedb.helper#954]
### Describe the bug

5.0.31~nexus now giving these errors when calling the recommendations window with:-
                          `Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info||5001|info=similar|true|info||5002|info=posters|true|browse,window_id=1191,$VAR[Type],$VAR[Query])`

```
2022-12-10 17:58:13.189 T:3523    error <general>: Unable to load window XML: /storage/.kodi/addons/skin.odin/xml/DialogNotification.xml. Line 0
                                                   Failed to open file
2022-12-10 17:58:13.236 T:3767    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: too many values to unpack (expected 2)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 17, in __init__
                                                       self.params = reconfigure_legacy_params(**parse_paramstring(self.paramstring))  # paramstring dictionary
                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.tmdbhelper/resources/modules/tmdbhelper/parser.py", line 52, in parse_paramstring
                                                       k, v = param.split('=')
                                                       ^^^^
                                                   ValueError: too many values to unpack (expected 2)
                                                   -->End of Python script error report<--
                                                   
2022-12-10 17:58:13.236 T:3764    error <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=videos&tmdb_type=movie&query=After Yang,year=2022&nextpage=false
2022-12-10 17:58:13.239 T:3523     info <general>: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
2022-12-10 17:58:13.240 T:3523    error <general>: Unable to load window XML: /storage/.kodi/addons/skin.odin/xml/DialogNotification.xml. Line 0
                                                   Failed to open file
2022-12-10 17:58:13.268 T:3763    error <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=cast&tmdb_type=movie&query=After Yang,year=2022&nextpage=false
2022-12-10 17:58:13.296 T:3769    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: too many values to unpack (expected 2)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/items/router.py", line 17, in __init__
                                                       self.params = reconfigure_legacy_params(**parse_paramstring(self.paramstring))  # paramstring dictionary
                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.tmdbhelper/resources/modules/tmdbhelper/parser.py", line 52, in parse_paramstring
                                                       k, v = param.split('=')
                                                       ^^^^
                                                   ValueError: too many values to unpack (expected 2)
                                                   -->End of Python script error report<--
```

### Steps To Reproduce

.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment]
Commas in unescaped titles/query

Error is caused by malformed RunScript line - so extra commas, two equals sign in a param, weird unescaped characters, empty vars etc

**Comment by jurialmunkey** [comment]
~Double check your skin code and make sure that you are NOT using runplugin.~

~If you definitely are using RunScript then it looks like some issue with the specific kodi nightly incorrectly routing via plugin.py rather than script.py~

Nope scrap that. Was right the first time. You've got an errant comma at end of the query.

This is why full logs are important rather than snippets. Really need to be able to see the surrounding context properly.

**Comment by jurialmunkey** [comment]
Wait... Do the list containers in your recommendations dialog have `<content>` tags with a plugin:// path? Because they shouldn't...

TMDbHelper fills the lists itself. If you're also adding `<content>` tags with a path then you're getting a conflict with Kodi also trying to fill the list. That's almost certainly the cause of all the issue you've been having.

**Comment by roidy** [comment]
> Commas in unescaped titles/query
>
> Nope scrap that. Was right the first time. You've got an errant comma at end of the query.
> 
> This is why full logs are important rather than snippets. Really need to be able to see the surrounding context properly.

Yep, I noticed the extra comma after posting but logging the two use variables returns no problems.

```
$VAR[Type] returns:- tmdb_type=movie
$VAR[Query] returns:- query=After Yang,year=2022

Runscript(plugin.video.themoviedb.helper,recommendations=5000|info=cast|true|info||5001|info=similar|true|info||5002|info=posters|true|browse,window_id=1191,tmdb_type=movie,query=After Yang,year=2022)
```

> Wait... Do the list containers in your recommendations dialog have < content > tags with a plugin:// path? Because they shouldn't... 

Yep, I know the content is filled by the plugin, so there are no content tags in my containers.

The code was working fine, except for this issue https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/950 The problem started with the update to 5.0.31~nexus, I will try rolling back to a previous version later and see if that fixes the issue.

**Comment by roidy** [comment]
I see 5.0.32 is out, I completely removed 5.0.31~nexus and did a fresh install of 5.0.32 and it now works fine except for https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/950 but that's a whole different issue :(

**Comment by jurialmunkey** [comment]
Really weird. I didn't make any changes that would affect this at all. 

I can't make sense of what would cause the error because query etc shouldn't even be in the plugin path at all. The recommendations window does the lookup first in the script and then adds the ID to the path instead. It never adds the query to the path. 

if you haven't added a content path and you haven't accidentally used Runplugin instead of RunScript then it just doesn't make any sense how it would be in the path.

Only thing I can think is that the addon.xml got messed up somehow and Kodi was trying to route it through the plugin rather than script side of things - that's the only way installing the new version could possibly make a difference that I can think of. Completely bizarre.
